name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: npm install, build, and test
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --list
    - run: npm install
    - run: npm run build
    - run: npm install --save gh-pages
    - run: npm run deploy
      env:
        CI: true
